# Generated by Django 5.2.16 on 2026-07-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('slug', models.SlugField(max_length=210, unique=True, verbose_name='slug')),
                ('short_description', models.CharField(max_length=255, verbose_name='description courte')),
                ('description', models.TextField(verbose_name='description')),
                ('featured_image', models.ImageField(blank=True, upload_to='products/', verbose_name='image principale')),
                ('product_type', models.CharField(choices=[('educational', 'Éducatif'), ('family', 'Familial'), ('business', 'Entreprise'), ('saas', 'SaaS'), ('other', 'Autre')], default='other', max_length=20, verbose_name='type de produit')),
                ('status', models.CharField(choices=[('concept', 'Concept'), ('in_development', 'En développement'), ('coming_soon', 'Bientôt disponible'), ('available', 'Disponible'), ('archived', 'Archivé')], default='concept', max_length=20, verbose_name='statut')),
                ('external_url', models.URLField(blank=True, verbose_name='lien externe')),
                ('is_featured', models.BooleanField(default=False, verbose_name='mis en avant')),
                ('is_published', models.BooleanField(default=False, verbose_name='publié')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name="ordre d'affichage")),
            ],
            options={
                'verbose_name': 'produit',
                'verbose_name_plural': 'produits',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['is_published'], name='products_pr_is_publ_12162e_idx'), models.Index(fields=['is_featured'], name='products_pr_is_feat_a5d7cd_idx'), models.Index(fields=['status'], name='products_pr_status_041708_idx'), models.Index(fields=['product_type'], name='products_pr_product_cea9e6_idx')],
            },
        ),
    ]
