# Generated by Django 5.2.16 on 2026-07-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('title', models.CharField(max_length=150, verbose_name='titre')),
                ('slug', models.SlugField(max_length=160, unique=True, verbose_name='slug')),
                ('short_description', models.CharField(max_length=255, verbose_name='description courte')),
                ('description', models.TextField(verbose_name='description')),
                ('icon', models.CharField(blank=True, help_text="Nom d'icône ou classe CSS (ex. : icon-web, bi-code-slash).", max_length=100, verbose_name='icône')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name="ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
                'ordering': ['display_order', 'title'],
                'indexes': [models.Index(fields=['is_active'], name='services_se_is_acti_91b7ea_idx'), models.Index(fields=['display_order'], name='services_se_display_381b7c_idx')],
            },
        ),
    ]
