# Generated by Django 5.2.16 on 2026-07-20 18:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('name', models.CharField(max_length=150, verbose_name='nom')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='adresse e-mail')),
                ('company', models.CharField(blank=True, max_length=150, verbose_name='entreprise')),
                ('subject', models.CharField(max_length=200, verbose_name='sujet')),
                ('message', models.TextField(verbose_name='message')),
                ('status', models.CharField(choices=[('new', 'Nouveau'), ('in_progress', 'En cours de traitement'), ('answered', 'Répondu'), ('archived', 'Archivé'), ('spam', 'Indésirable')], default='new', max_length=20, verbose_name='statut')),
                ('is_read', models.BooleanField(default=False, verbose_name='lu')),
            ],
            options={
                'verbose_name': 'message de contact',
                'verbose_name_plural': 'messages de contact',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='contact_con_status_fa3e24_idx'), models.Index(fields=['is_read'], name='contact_con_is_read_9a011e_idx')],
            },
        ),
    ]
