# Generated by Django 5.2.16 on 2026-07-20 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nom')),
                ('slug', models.SlugField(max_length=110, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'technologie',
                'verbose_name_plural': 'technologies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('slug', models.SlugField(max_length=110, unique=True, verbose_name='slug')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name="ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'catégorie de projet',
                'verbose_name_plural': 'catégories de projet',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['is_active'], name='portfolio_p_is_acti_76c89f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('slug', models.SlugField(max_length=210, unique=True, verbose_name='slug')),
                ('short_description', models.CharField(max_length=255, verbose_name='description courte')),
                ('description', models.TextField(verbose_name='description')),
                ('featured_image', models.ImageField(upload_to='portfolio/', verbose_name='image principale')),
                ('client_name', models.CharField(blank=True, max_length=150, verbose_name='nom du client')),
                ('project_url', models.URLField(blank=True, verbose_name='lien du projet')),
                ('github_url', models.URLField(blank=True, verbose_name='lien GitHub')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='date de réalisation')),
                ('status', models.CharField(choices=[('in_progress', 'En cours'), ('completed', 'Terminé'), ('maintenance', 'En maintenance'), ('concept', 'Concept')], default='completed', max_length=20, verbose_name='statut')),
                ('is_featured', models.BooleanField(default=False, verbose_name='mis en avant')),
                ('is_published', models.BooleanField(default=False, verbose_name='publié')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name="ordre d'affichage")),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='portfolio.projectcategory', verbose_name='catégorie')),
                ('technologies', models.ManyToManyField(blank=True, related_name='projects', to='portfolio.technology', verbose_name='technologies')),
            ],
            options={
                'verbose_name': 'projet',
                'verbose_name_plural': 'projets',
                'ordering': ['display_order', '-completion_date', 'title'],
                'indexes': [models.Index(fields=['is_published'], name='portfolio_p_is_publ_8e4b3f_idx'), models.Index(fields=['is_featured'], name='portfolio_p_is_feat_f965da_idx'), models.Index(fields=['status'], name='portfolio_p_status_e2a3b4_idx')],
            },
        ),
    ]
